### ISSUE TITLE
Cloud not install with Redmine 2.4.2

### ISSUE THREAD

**Issue by mikoto20000** [backlogs/redmine_backlogs#1020]
Install plugin failed with Redmine 2.4.2 cause of gem's conflict.

Following modification make backlogs installl for RM 2.4.2.
But it may break for other version.

```
--- a/Gemfile
+++ b/Gemfile
@@ -10,7 +10,7 @@ RAILS_VERSION_IS_3 = rails3 =~ deps['rails']

 gem "holidays", "~>1.0.3"
 gem "icalendar"
-gem "nokogiri", "< 1.6.0"
+gem "nokogiri"
 gem "open-uri-cached"
 gem "prawn"
 gem 'json'
```

**Comment by myrjola** [comment]
Hi! We started using Backlogs master-branch in a RM 2.4.2 production environment. I'll be in touch if we encounter any issues.

**Comment by forfront** [comment]
Hi Dose Bakclogs support Redmine 5 or redmine4 please? I tried installing the redmine_backlog 1.06. but it conflicts with latest gem files.
