### ISSUE TITLE
bug with redmine 1.3.0

### ISSUE THREAD

**Issue by unglevan** [backlogs/redmine_backlogs#1070]
I have flowing bug when setup with 
redmine 1.3.0. 
ruby 1.8.7 (2012-02-08 patchlevel 358) [x86_64-linux]
Rails 2.3.14
backlog: V1.0.6
Plz help me
/var/lib/redmine/vendor/plugins/redmine_backlogs/app/models/rb_release.rb:59: syntax error, unexpected '.', expecting kEND .order(:day).group(:day).sum(:total_points) ^ /var/lib/redmine/vendor/plugins/redmine_backlogs/app/models/rb_release.rb:61: syntax error, unexpected '.', expecting kEND .order(:day).group(:day).sum(:added_points) ^ /var/lib/redmine/vendor/plugins/redmine_backlogs/app/models/rb_release.rb:63: syntax error, unexpected '.', expecting kEND .order(:day).group(:day).sum(:closed_points) ^

**Comment by achiinto** [comment]
Isn't Redmine Backlogs only works with Redmine version 2+ ? I thought it was designed to work with Rails 3.

**Comment by patrickatamaniuk** [comment]
redmine 1.x is not working with backlogs, support was dropped long ago. There is some Rails2 code in there, but it is not working.
