### ISSUE TITLE
"Loading..." never disapperars

### ISSUE THREAD

**Issue by eXtreemru** [backlogs/redmine_backlogs#1088]
I know, that i should only use Redmine	2.2.4 or 2.3.2 for backlogs v1.0.6, but i have no chance to downgrade our installation so i use backlogs v1.0.6 with Redmine 2.6.1.

The issue is, once user story is being moved to the sprint: if you directly to the issue (view/edit) the "Loading..." thing never disappears. This is reproducable for all projects with backlogs-module enabled

Once you move the story back to the product backlog - eveything is fine again.

Here is what i get with firebug:
"TypeError: $.jqplot.ElemContainer is undefined
$.jqplot.ElemContainer.call(this);
"
it is the 5th error i get on this page. Other 4 are present everywhere on backlogs, but they do not cause any other issues:

here are all 5 listed:
jquery....1410882 (line 398, col 4)
TypeError: $.jqplot.eventListenerHooks is undefined
	

$.jqplot.eventListenerHooks.push(['jqplotMouseMove', handleMove]);

	
jqplot....1410882 (line 32, col 4)
TypeError: c.jqplot.TableLegendRenderer is not a constructor
	

...jqplot.EnhancedLegendRenderer.prototype=new c.jqplot.TableLegendRenderer();c.jqp...

	
jqplot....1410882 (line 57, col 139)
TypeError: h.jqplot.LinearAxisRenderer is not a constructor
	

...,v]}h.jqplot.DateAxisRenderer.prototype=new h.jqplot.LinearAxisRenderer();h.jqpl...

	
jqplot....1410882 (line 57, col 819)
TypeError: $.jqplot.ElemContainer is undefined
	

$.jqplot.ElemContainer.call(this);

	

For the case you do not continues fixing it for higher redmine version - could some1 suggest a hotfix? this "Loading..." staying always in the middle of the screen is simply annoying

**Comment by necramirez** [comment]
I'm in the same situation, RB 1.0.6 on Redmine 2.6, and I also see the floating "Loading..." thing.

**Comment by roed** [comment]
This is a temporary fix:

Inlcude this file:
http://code.jquery.com/jquery-migrate-1.2.1.js

In this file:
redmine_backlogs/app/views/hooks/_rb_include_scripts.html.erb

Works for us

**Comment by necramirez** [comment]
@roed -- thanks for that, it also worked for us

**Comment by eXtreemru** [comment]
Meanwhile we have created another redmine installation with redmine 2.3.2, since we found some other issues, like problems with multiview graphs. However thank you for the hotfix!

**Comment by achiinto** [comment]
Have anyone looked further into what caused the "loading" to occur? I think the hotfix only hide the "loading" but there are other issues with redmine that making it not functioning 100%.

**Comment by achiinto** [comment]
I guess, alternatively, removing jqplot altogether and then disable burn-down from redmine_backlog will no longer show the errors. The problem is that Redmine Backlog is dependent on jqplot for plotting the burn-down graphs. However, jqplot has not been updated for a long time. It does not support Jquery 2.0. If Redmine Backlog is to support future versions of Redmine and the on going upgrades, it will need other graphing library. Or to not support burn-down visualization altogether.

**Comment by arthur24b6** [comment]
I forked this with the fix described here: https://github.com/arthur24b6/redmine_backlogs/commit/2c4a6eafff62eb25943971d9667413c7dabf9280
