### ISSUE TITLE
Does backlog 1.0.6 supports redmine 2.6.5?

### ISSUE THREAD

**Issue by nirmalk1231** [backlogs/redmine_backlogs#1102]
Does backlog 1.0.6 supports redmine 2.6.5?
or any other work around for the same

**Comment by cmuller** [comment]
I do not know for 2.6.5 but we are successfully using backlogs v1.0.6 with redmine 2.6.1.stable.
hope it'll help.

**Comment by samueldc** [comment]
Hi cmuller,
Could you please post you environmental information? Mine is as follows and I'm unable to install backlogs:
```
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p547 (2014-05-14) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.4
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.11
  redmine_custom_workflows       0.0.4
  redmine_external_wiki_link     0.0.1
  redmine_mylyn_connector        2.8.2.stable
```

The redmine crashes after resolving all the dependencies required by backlogs.

**Comment by samueldc** [comment]
I'm not sure, but looks like backlogs development was stranded. Any thoughts?

**Comment by cmuller** [comment]
here it is:

~~~
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Mercurial                      1.4
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_backlogs               v1.0.6
  redmine_changeauthor           1.0.0
  redmine_didyoumean             1.2.0
  redmine_dmsf                   1.4.9 stable
  redmine_googlesss              0.0.2
  redmine_importer               1.2
  redmine_improved_searchbox     0.0.3
  redmine_issue_history_tabs     0.0.3
  redmine_lightbox               0.0.8
  redmine_pastebin               0.2.0
  redmine_plugin_views_revisions 0.0.1
  redmine_subtasks_inherited_fields 0.0.3
  redmine_tab                    0.4.0
  redmine_user_issues            0.0.2
  redmine_wiki_extensions        0.6.5
  redmine_wiki_lists             0.0.3
  redmine_xls_export             0.2.1.t7
  sidebar_hide                   0.0.7
~~~

We are using the latest version of backlogs with Redmine 2.6.1. Please note that sometimes multiple plugins are either mutually exclusive (e.g., they patch the same piece of core) or they both use the same ruby library but with different version specification. And ruby is very annoying with this: it can't solve that >=1.2 and >=1.3 is ok if you just take the second; specs have to be exactly the same at string level.. :-( In this case, you have to modify a bit the Gemfiles (I had to do it for nokogiri used by both backlogs and DMSF).
So you might want to try an install with just Redmine core, then backlogs plugin, then adding other plugins one by one to see if it still works.
If you want I can send you the ansible scripts that I am using. It is pretty straightforward to guess what each line is doing.

Hope it'll help.

**Comment by samueldc** [comment]
Thank you so much! You gave me a lot of hints.

**Comment by samueldc** [comment]
Cmuller,

I would really appreciate if you could send your scripts.

**Comment by samueldc** [comment]
Thanks, I got it already.

**Comment by nirmalk1231** [comment]
we shifted to agile plugin 
thanks every one for your support
