### ISSUE TITLE
Does it support redmine3.3.x?

### ISSUE THREAD

**Issue by iwatobipen** [backlogs/redmine_backlogs#1137]
Dear,
Does the plug in work at redmine 3.3.x？
I found some documents about 3.2.x but could not find about 3.3.x .
Thank you.

**Comment by futaz** [comment]
There is a branch named `feature/redmine3` which is compatible with Redmine 3.3.1. We use it on ruby 2.3 and everything works fine!
As I can remember, there was two dependency conflict (`capybara` and `nokogiri` gems), but I simply commented out the older ones.

**Comment by iwatobipen** [comment]
Dear futaz,

Thank you for your quick reply.
I tried to install backlogs using feature/redmine3 branch and it worked well. ;-)

Kind regards,
Takayuki

**Comment by hxqqqqqq** [comment]
Dear futaz and iwatobipen,

when i add one story, the error tips:
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where id = 14' at line 1: update issues set position = where id = 14
what can i do?who can help me?

**Comment by futaz** [comment]
Dear hxqqqqqq!

Please report it in a new issue and provide more information:
How can I reproduce the problem?
Include the problematic sql statement, the exact version of ruby, redmine, and database!

Then you can link that issue here, so I will be notified about it.

**Comment by mtolava** [comment]
> Dear futaz and iwatobipen,
> 
> when i add one story, the error tips:
> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where id = 14' at line 1: update issues set position = where id = 14
> what can i do?who can help me?

I have the same error.
Installing the feature/redmine3 branch solve the problem.
I am migrating redmine from 2.6 to 3.3, I must migrate the database again, and then perform the redmine:plugins:migrate again and it works fine
