### ISSUE TITLE
Cannot export story points via REST API

### ISSUE THREAD

**Issue by alizzi** [backlogs/redmine_backlogs#439]
Hi, 

First of all sorry if this is not an issue..

We are using Backlog plug-in, and it is very suitable for what we do. We are trying to export issues from Redmine via REST API to special Reports and we really need the story points exported as any other custom field..

Do yo know how can we configure backlogs in order to get the story points field get exported as the rest of custom fields

Regards!
Adrián

**Comment by XianZhengquan** [comment]
I need to get story_points for this interface /issues/{issueId}.json, including GET and POST
