### ISSUE TITLE
Migration problems

### ISSUE THREAD

**Issue by stangls** [backlogs/redmine_backlogs#781]
platform:  # supported: 2.0.4, 2.1.5, 2.2.0
backlogs:  # supported: 0.9.32
ruby:  # supported: 1.9.3, 1.8.7

Hi

I get an error during migration (see appendix).
Redmine: 1.4.4
Ruby: 4.9
Rake: 0.9.2.2
On branches: master, v0.9.32, stable

---

Appendix:

Migrating redmine_backlogs...
==  RbAddHistory: migrating ===================================================
Rebuilding history...
    40 (     1/1701)...
rake aborted!
An error has occurred, all later migrations canceled:

private method `select' called for nil:NilClass
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:298:in`touch_sprint'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in`call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:93:in `block in run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in`each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:276:in`run_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:344:in `callback'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:251:in`create_or_update_with_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:2577:in `save'
/usr/lib/ruby/vendor_ruby/active_record/validations.rb:1089:in`save_with_validation'
/usr/lib/ruby/vendor_ruby/active_record/dirty.rb:79:in `save_with_dirty'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:229:in`block in with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:182:in`transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:228:in `with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in`block in save_with_transactions'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:208:in `rollback_active_record_state!'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in`save_with_transactions'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:1972:in `find_or_create_by_issue_id'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:1979:in`method_missing'
/usr/share/redmine/vendor/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:28:in `history'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:317:in`update_parent'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:178:in `evaluate_method'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in`call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:93:in `block in run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in`each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:276:in`run_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:344:in `callback'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:267:in`create_with_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:2927:in `create_or_update'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:250:in`create_or_update_with_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:2577:in `save'
/usr/lib/ruby/vendor_ruby/active_record/validations.rb:1089:in`save_with_validation'
/usr/lib/ruby/vendor_ruby/active_record/dirty.rb:79:in `save_with_dirty'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:229:in`block in with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:182:in`transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:228:in `with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in`block in save_with_transactions'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:208:in `rollback_active_record_state!'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in`save_with_transactions'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:241:in `rebuild_issue'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:259:in`block in rebuild'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:257:in `each'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:257:in`each_with_index'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:257:in `rebuild'
/usr/share/redmine/vendor/plugins/redmine_backlogs/db/migrate/038_rb_add_history.rb:27:in`up'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:282:in `block in migrate'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in`measure'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:282:in `migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:365:in`migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:491:in `block (2 levels) in migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:567:in`call'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:567:in `ddl_transaction'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:490:in`block in migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:477:in `each'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:477:in`migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:401:in `up'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:383:in`migrate'
/usr/share/redmine/vendor/plugins/engines/lib/engines/plugin/migrator.rb:20:in `migrate_plugin'
/usr/share/redmine/vendor/plugins/engines/lib/engines/plugin.rb:93:in`migrate'
/usr/share/redmine/lib/tasks/migrate_plugins.rake:8:in `block (3 levels) in <top (required)>'
/usr/share/redmine/lib/tasks/migrate_plugins.rake:5:in`each'
/usr/share/redmine/lib/tasks/migrate_plugins.rake:5:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:228:in`call'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:228:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:223:in`each'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:223:in `execute'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:159:in`invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:143:in`invoke_task'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in`each'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:110:in`run_with_threads'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:73:in`block in run'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-0.9.6/lib/rake/application.rb:70:in`run'
/var/lib/gems/1.9.1/gems/rake-0.9.6/bin/rake:37:in `<top (required)>'
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate_plugins

**Comment by jyoti2092** [comment]
Hi, I'm facing the same issue after migration. I'm using an application built in Ruby. Please let me know what is the solution

Thanks
