### ISSUE TITLE
performance problem with issue update

### ISSUE THREAD

**Issue by rlisowski** [backlogs/redmine_backlogs#998]
platform: 2.3.3
backlogs: 1.0.5, master (9032c8d)
ruby: 1.9.3-p429

I have issue in RM with ~35 subtasks (5 new, 30 closed), when I change "Target Version" attribute on that task it takes more that 5 minutes and browser timeouts. I noticed in logs that when I change parent issue, all subtasks are updated too.
There is also big amount of DB requests. They are executed for each subtask few times eg:

```
  Issue Load (0.4ms)  SELECT `issues`.* FROM `issues` WHERE `issues`.`id` = 83672 LIMIT 1
  CACHE (0.0ms)  SELECT `trackers`.* FROM `trackers` WHERE `trackers`.`id` IN (4, 5)
  CACHE (0.0ms)  SELECT `trackers`.* FROM `trackers` WHERE `trackers`.`id` IN (4, 5)
  IssueStatus Load (0.1ms)  SELECT `issue_statuses`.* FROM `issue_statuses` WHERE `issue_statuses`.`id` = 3 LIMIT 1
  CACHE (0.0ms)  SELECT `trackers`.* FROM `trackers` WHERE `trackers`.`id` IN (4, 5)
  CACHE (0.0ms)  SELECT `versions`.* FROM `versions` WHERE `versions`.`id` = 526 LIMIT 1
  RbIssueHistory Load (0.2ms)  SELECT `rb_issue_history`.* FROM `rb_issue_history` WHERE `rb_issue_history`.`issue_id` = 83708 LIMIT 1
```

Any idea how can I make issue update faster?

Kind Regards

**Comment by ippeiukai** [comment]
FYI, following https://github.com/backlogs/redmine_backlogs/issues/998#issuecomment-31728148 , here is what I did: 

https://github.com/backlogs/redmine_backlogs/compare/v1.0.6...ippeiukai:after_save_delayed_job

Migration should be ran via redmine:plugins:migrate rake task.
The init script at `plugins/redmine_backlogs/script/delayed_job-init_d` is for redhat-like systems and can be customised for your installation (redmine directory and daemon user) and registered to the system  with chkconfig etc.
